### PR TITLE
poking at the operator overloads to try and get MSVC 2015 building

### PR DESCRIPTION
**Pull request by mwiebe**
Filling in operators seems to just lead deeper down a rabbits hole, though.

### CODE REVIEW

**Comment by mwiebe** [comment]
It looks to me like something is broken about the SFINAE that should be happening within `has_make`, but not sure about the details yet.

**Comment by izaid** [comment]
FYI, std::common_type is already overloaded for the complex types in complex.hpp

**Comment by izaid** [comment]
@mwiebe I think this can be closed now.

**Comment by insertinterestingnamehere** [comment]
Agreed. We may want to keep the int128 multiplication commit though.

**Comment by izaid** [comment]
Closing this, because we've had MSVC 2015 working for some time.

**Pull request closed without merging**
