### PR TITLE
MSVC 2015 build fix attempt

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
Here's my attempt at fixing the issues with MSVC 2015. All I've managed to do thus far is change the nature of the errors the compiler spits out.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Okay, my goal here was to find a small workaround rather than adding a lot of extra code. I have it down to 3 errors, but am struggling to get it any further. I'll leave it open for reference while we work on getting this fixed. Mark's larger refactoring in https://github.com/libdynd/libdynd/pull/531 is probably the way to go.

**Comment by insertinterestingnamehere** [comment]
I now have a msvc 2013 environment working, so at least this is no longer causing problems for the visibility fixes.

**Comment by mwiebe** [comment]
Let's merge this then, and continue with 2015 separately.

**Comment by insertinterestingnamehere** [comment]
Ah, sorry I wasn't clear, getting 2013 working on my end stemmed from getting the environment for it working properly and was independent of these changes. There's little or no net gain from this PR for the repository in general other than a small reduction in the number of msvc2015 errors we're seeing. Aside from that, this is just a handful of unnecessary special cases. I'll open a PR that reverts it.

**Pull request merged**
