### PR TITLE
Updated Google Benchmark

### PR DESCRIPTION
**Pull request by izaid**

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Now that google benchmark and google test are on github too, why don't we just include them as git submodules?

**Comment by izaid** [comment]
We should definitely do that.

**Comment by izaid** [comment]
@insertinterestingnamehere Good suggestion, just did this for benchmark. The only downside is people need to specify --recursive when cloning.

**Comment by insertinterestingnamehere** [comment]
@izaid Cool. I'm glad we have that working now. The recursive clone is unfortunate though.

**Pull request merged**
