### PR TITLE
[WIP] Making elwise_reduce consistent with other arrfunc functionality

### PR DESCRIPTION
**Pull request by mwiebe**

### CODE REVIEW

**Comment by izaid** [comment]
@mwiebe Can we get these merged, at least partially?

**Comment by mwiebe** [comment]
@izaid the build error is gone, but the flow of resolve_dst_type et al isn't quite complete yet

**Comment by izaid** [comment]
Thanks! I can take it from here if you'd rather.

**Comment by izaid** [comment]
Closing because we are moving to my branch.

**Pull request closed without merging**
