### PR TITLE
Parallel Compilation

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This enables parallel compilation in the Travis CI build.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Okay, enabling parallel compilation for msvc made appveyor terribly slow, so that'll just have to be done via the arguments to cmake for now.

**Comment by insertinterestingnamehere** [comment]
I just enabled parallel building for the conda build as well. I haven't taken the time to make the number of threads an option. I just set it to default at 5 so that it will run well on the two-core Travis CI machines. @izaid any thoughts on that?

**Comment by izaid** [comment]
Wow, is it actually twice as fast with clang? That's impressive, feel free to merge so long as nothing is terribly slow.

**Comment by insertinterestingnamehere** [comment]
The only slowdown was because appveyor couldn't handle running msvc with the -MP flag. On my windows machine doing that speeds up compilation dramatically, but the single-core appveyor bot wouldn't have anything of it, so I removed that change. Merging now.

**Comment by mwiebe** [comment]
I wonder if it's worth using http://www.cmake.org/cmake/help/v3.0/module/ProcessorCount.html to set the default?

**Comment by insertinterestingnamehere** [comment]
Yep, we could definitely do some kind of dynamic processor detection in the conda build. There really isn't any point in doing that in the Travis build. On the other hand, the conda build calls cmake and then make, so setting the number of cores automatically may need to be done in shell. I haven't found any way to have cmake set the default number of threads for a makefile yet.

**Comment by insertinterestingnamehere** [comment]
Okay, I took a shot at it in https://github.com/libdynd/libdynd/pull/540.

**Pull request merged**
