### PR TITLE
clang-format string-related files

### PR DESCRIPTION
**Pull request by mdboom**
This is a formatting-only change to fixup the string-related stuff I've been working on recently.

(This will need to be done to #951 as well after this is merged).

### CODE REVIEW

**Comment by mdboom** [comment]
Rebased.

**Comment by mdboom** [comment]
Rebased again

**Comment by mdboom** [comment]
I *think* the Travis failure is unrelated...

**Comment by izaid** [comment]
It is. It's a very specific error just for Clang on Linux that @insertinterestingnamehere is sorting out.

**Pull request merged**
