### PR TITLE
[WIP] Option type failure

### PR DESCRIPTION
**Pull request by izaid**
This demonstrates the option type test failures on Windows.

### CODE REVIEW

**Comment by mwiebe** [comment]
Something strange going on here, it ends up calling instantiate for an RNG kernel:

```
 	test_libdynd.exe!dynd::nd::random::detail::uniform_kernel<4,2,std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> >::instantiate(char * __formal, unsigned __int64 __formal, char * __formal, void * ckb, __int64 ckb_offset, const dynd::ndt::type & __formal, const char * __formal, __int64 __formal, const dynd::ndt::type * __formal, const char * const * __formal, unsigned int kernreq, const dynd::eval::eval_context * __formal, const dynd::nd::array & kwds, const std::map<dynd::nd::string,dynd::ndt::type,std::less<dynd::nd::string>,std::allocator<std::pair<dynd::nd::string const ,dynd::ndt::type> > > & __formal) Line 79	C++
 	test_libdynd.exe!instantiate_option_to_value_assignment_kernel(char * __formal, unsigned __int64 __formal, char * __formal, void * ckb, __int64 ckb_offset, const dynd::ndt::type & dst_tp, const char * dst_arrmeta, __int64 nsrc, const dynd::ndt::type * src_tp, const char * const * src_arrmeta, unsigned int kernreq, const dynd::eval::eval_context * ectx, const dynd::nd::array & kwds, const std::map<dynd::nd::string,dynd::ndt::type,std::less<dynd::nd::string>,std::allocator<std::pair<dynd::nd::string const ,dynd::ndt::type> > > & tp_vars) Line 263	C++
 	test_libdynd.exe!dynd::kernels::make_option_assignment_kernel(void * ckb, __int64 ckb_offset, const dynd::ndt::type & dst_tp, const char * dst_arrmeta, const dynd::ndt::type & src_tp, const char * src_arrmeta, unsigned int kernreq, const dynd::eval::eval_context * ectx) Line 509	C++
 	test_libdynd.exe!dynd::ndt::option_type::make_assignment_kernel(void * ckb, __int64 ckb_offset, const dynd::ndt::type & dst_tp, const char * dst_arrmeta, const dynd::ndt::type & src_tp, const char * src_arrmeta, unsigned int kernreq, const dynd::eval::eval_context * ectx) Line 375	C++
 	test_libdynd.exe!dynd::make_assignment_kernel(void * ckb, __int64 ckb_offset, const dynd::ndt::type & dst_tp, const char * dst_arrmeta, const dynd::ndt::type & src_tp, const char * src_arrmeta, unsigned int kernreq, const dynd::eval::eval_context * ectx) Line 171	C++
```

**Comment by izaid** [comment]
That is super weird. It's also really weird that all Travis CI tests pass. Is it possible that MSVC is actually compiling things wrong?

**Comment by mwiebe** [comment]
This code fails to compile in the MSVC 2015 RC, so I wouldn't be surprised by that at all.

**Comment by mwiebe** [comment]
I've figured out a workaround, which is to replace the is_avail_kernel alias template with inheritance.

```
// is_avail_kernel.hpp line 379
  // With this, it fails
  template <type_id_t Src0TypeID>
  using is_avail_kernel =
      detail::is_avail_kernel<Src0TypeID, type_kind_of<Src0TypeID>::value>;
  // Replaced with this, it succeeds
  template <type_id_t Src0TypeID>
  struct is_avail_kernel
      : public detail::is_avail_kernel<Src0TypeID,
                                       type_kind_of<Src0TypeID>::value> {
  };
```

**Comment by izaid** [comment]
Thanks! We'll add template aliases to the long list of things that MSVC can't handle.

**Comment by izaid** [comment]
Fixed in master now.

**Pull request closed without merging**
