### PR TITLE
Try using the new container-based system on the Travis CI server.

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This is mostly experimental to see if, and how well this works. I've disabled the Python build for now since it wasn't clear to me how to get libdynd in the right place to be used by dynd-python without sudo access.

### CODE REVIEW

**Comment by izaid** [comment]
Ha, this is awesome! We've been talking about doing this for a while, but have been held back because we didn't think we could install everything without sudo. Massive +1 if you can do it.

**Comment by insertinterestingnamehere** [comment]
Thanks, I noticed that the SciPy devs got theirs working recently, so I'm feeling hopeful :)

**Comment by insertinterestingnamehere** [comment]
Okay, except for the Python build, this is working. I've currently removed the Python build since it tends to fail all the time. If you'd like, I can figure out how to re-add it or re-add it as an allow-fail block so it can run and fail without making the indicator for the whole PR fail. Thoughts?

**Comment by insertinterestingnamehere** [comment]
Okay, I haven't figured out how to get the Python build running yet. I'll try a few more things tomorrow. The latest version is my most recent attempt. It has all the others commented out to let me debug faster. Other than that, all the builds that use only C++ work fine.

**Comment by izaid** [comment]
Okay, it's awesome that everything is working besides Python. That being said, I don't think we can drop the Python build -- it is too useful. We use it to determine if we broke the Python bindings and need to fix them, which happens frequently.

**Comment by izaid** [comment]
@insertinterestingnamehere I merged the dynd-python PR and reran Travis, but it seems we're getting a segmentation fault at the test stage.

**Comment by insertinterestingnamehere** [comment]
@izaid This looks like the segfault we were seeing with clang the other day. I'm baffled as to why it is only showing up on the new infrastructure and not on the current clang builds. I'll try enabling the verbose output and see if there are any differences in the flags.

**Comment by izaid** [comment]
@insertinterestingnamehere Agreed. I think this segfault is now a major issue we need to solve. I'm also seeing a segfault on anaconda.org, although that is using gcc. I wonder if it is the same.

**Comment by insertinterestingnamehere** [comment]
Hmm, rebuilding numpy with clang didn't fix it either. I'm not sure if this could show up with gcc. I'll try running the travis build here using gcc.

**Comment by insertinterestingnamehere** [comment]
Okay, this all works with gcc. If you'd like I can re-enable the other builds and we can merge this for now.

**Comment by izaid** [comment]
Wait, so do all the builds work?

**Comment by insertinterestingnamehere** [comment]
Yep, I just commented the others out to speed up debugging the Python build. The Python build works with gcc but not with clang.

**Comment by izaid** [comment]
Okay, we'll definitely merge this but I'd like to see if I can sort out the clang issue first.

**Comment by izaid** [comment]
Oh, wait, are you saying that you want me to merge this now to help with sorting out the clang issue with Python? In that case I'll do it now.

**Comment by insertinterestingnamehere** [comment]
Not really, I need to re-enable the other builds first. We could do that if
you'd like though.

**Comment by izaid** [comment]
@insertinterestingnamehere I believe I just fixed the clang issue, at least on my local machine. I've merged a change into dynd-python. Do you want to try again now?

**Comment by insertinterestingnamehere** [comment]
Fantastic! Yes, I'll switch this build back to clang and see if that fixes
it. Thanks!

**Comment by insertinterestingnamehere** [comment]
Okay, the clang build works here now. I'll re-enable the other builds and get a similar PR up for dynd-python.

**Comment by insertinterestingnamehere** [comment]
Alright, let's see if this works. Once the builds pass again this should be good to go.

**Comment by insertinterestingnamehere** [comment]
Alright, this is done. Thanks!

**Comment by izaid** [comment]
Fantastic work!

**Pull request merged**
