### PR TITLE
Remove various unused variables to prevent compilation failures.

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**

### CODE REVIEW

**Comment by izaid** [comment]
Sorry about that -- I merged with haste. My PR for dynd-python contains the Python fixes.

**Comment by insertinterestingnamehere** [comment]
No worries. I ran across this while trying to see if some of my fixes for Windows had helped the situation. Feel free to merge whenever is good for you.

**Comment by izaid** [comment]
I ended up fixing this in a separate PR (already merged), so feel free to close.

**Comment by insertinterestingnamehere** [comment]
The two sets of changes look good to me

**Pull request closed without merging**
