### PR TITLE
libdynd-config: add -libndname and -libndtname.

### PR DESCRIPTION
**Pull request by skrah**
This is mostly for use in dynd-python (pull request follows).

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
This looks good to me. That said, I'm not sure we want to move from libdynd and libdyndt to libnd and libndt. It'd be good to keep with the more verbose naming convention for now, at least for the sake of consistency.

**Comment by izaid** [comment]
Yeah, while I don't like libdyndt, Ian is right. Consistency for now, proper fixes for later.

**Comment by skrah** [comment]
Yes, it's probably better to use the official names.

**Comment by izaid** [comment]
I'm happy to merge this in. @mwiebe, this cool?

**Comment by mwiebe** [comment]
Looks good to me

**Comment by izaid** [comment]
Merged, thanks @skrah

**Pull request merged**
